/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apollo_project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import keeptoo.KButton;

/**
 *
 * @author vetri
 */
public class ViewStudent_row_data extends javax.swing.JFrame {

    /**
     * Creates new form viewStudent
     */
    public ViewStudent_row_data() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(this);
        setTitle("Students Record");

        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);
        jDateChooser_dob.setEnabled(false);
        jDateChooser_certificate.setEnabled(false);

    }
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    String reference;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstname_label = new javax.swing.JLabel();
        text_firstName = new javax.swing.JTextField();
        text_fatherName = new javax.swing.JTextField();
        mobile_label = new javax.swing.JLabel();
        text_mobileNo = new javax.swing.JTextField();
        dob_label = new javax.swing.JLabel();
        jDateChooser_dob = new com.toedter.calendar.JDateChooser();
        course_label1 = new javax.swing.JLabel();
        text_courseName = new javax.swing.JTextField();
        course_label2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        text_duration = new javax.swing.JTextField();
        text_timing = new javax.swing.JTextField();
        reference_label = new javax.swing.JLabel();
        text_reference = new javax.swing.JTextField();
        text_staffname = new javax.swing.JTextField();
        staffname_label = new javax.swing.JLabel();
        fathersname_label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CourseStatus_list = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        certificateStatus_list = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser_certificate = new com.toedter.calendar.JDateChooser();
        dob_label1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateRecords_btn = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        btn_minimize = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selected Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstname_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-contacts-filled-30.png"))); // NOI18N
        jPanel1.add(firstname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        text_firstName.setEditable(false);
        text_firstName.setBackground(new java.awt.Color(255, 255, 255));
        text_firstName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        text_firstName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.add(text_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 50));

        text_fatherName.setEditable(false);
        text_fatherName.setBackground(new java.awt.Color(255, 255, 255));
        text_fatherName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        text_fatherName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Father's Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.add(text_fatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 37, 220, 50));

        mobile_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-phone-30.png"))); // NOI18N
        jPanel1.add(mobile_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 236, -1, -1));

        text_mobileNo.setEditable(false);
        text_mobileNo.setBackground(new java.awt.Color(255, 255, 255));
        text_mobileNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        text_mobileNo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mobile Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.add(text_mobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 228, 220, 50));

        dob_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-planner-30.png"))); // NOI18N
        jPanel1.add(dob_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jDateChooser_dob.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser_dob.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jDateChooser_dob.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jDateChooser_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 132, 220, 60));

        course_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-singing-30.png"))); // NOI18N
        jPanel1.add(course_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 146, -1, -1));

        text_courseName.setEditable(false);
        text_courseName.setBackground(new java.awt.Color(255, 255, 255));
        text_courseName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        text_courseName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        text_courseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_courseNameActionPerformed(evt);
            }
        });
        jPanel1.add(text_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 126, 221, 50));

        course_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-time.png"))); // NOI18N
        jPanel1.add(course_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 361, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Duration & Time Track", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        text_duration.setEditable(false);
        text_duration.setBackground(new java.awt.Color(255, 255, 255));
        text_duration.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        text_duration.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Duration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        text_timing.setEditable(false);
        text_timing.setBackground(new java.awt.Color(255, 255, 255));
        text_timing.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        text_timing.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Timing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_timing, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(text_duration)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(text_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_timing, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 313, -1, -1));

        reference_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-form.png"))); // NOI18N
        jPanel1.add(reference_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 246, -1, -1));

        text_reference.setEditable(false);
        text_reference.setBackground(new java.awt.Color(255, 255, 255));
        text_reference.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        text_reference.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reference Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        text_reference.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_referenceKeyReleased(evt);
            }
        });
        jPanel1.add(text_reference, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 228, 211, 50));

        text_staffname.setEditable(false);
        text_staffname.setBackground(new java.awt.Color(255, 255, 255));
        text_staffname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        text_staffname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Staff Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.add(text_staffname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 220, 50));

        staffname_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-contacts-filled-30.png"))); // NOI18N
        jPanel1.add(staffname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        fathersname_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-administrator-male-30.png"))); // NOI18N
        jPanel1.add(fathersname_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 43, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-moleskine-30.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, 40));

        CourseStatus_list.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CourseStatus_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-------------Select------------->", "Completed", "Not-Completed" }));
        CourseStatus_list.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 204)));
        CourseStatus_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseStatus_listMouseClicked(evt);
            }
        });
        CourseStatus_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseStatus_listActionPerformed(evt);
            }
        });
        jPanel1.add(CourseStatus_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-certificate-30.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Course Status");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 90, -1));

        certificateStatus_list.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        certificateStatus_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-------------Select------------->", "Issued ", "Not-Issued" }));
        certificateStatus_list.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 204)));
        certificateStatus_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                certificateStatus_listMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                certificateStatus_listMousePressed(evt);
            }
        });
        certificateStatus_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateStatus_listActionPerformed(evt);
            }
        });
        certificateStatus_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                certificateStatus_listKeyPressed(evt);
            }
        });
        jPanel1.add(certificateStatus_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 210, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Certificate Status");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 120, -1));

        jDateChooser_certificate.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser_certificate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 204)));
        jDateChooser_certificate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jDateChooser_certificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 210, 40));

        dob_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-planner-30.png"))); // NOI18N
        jPanel1.add(dob_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Issued Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 140, -1));

        updateRecords_btn.setText("Update Record");
        updateRecords_btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateRecords_btn.setkBackGroundColor(new java.awt.Color(0, 255, 0));
        updateRecords_btn.setkBorderRadius(30);
        updateRecords_btn.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        updateRecords_btn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        updateRecords_btn.setkHoverStartColor(new java.awt.Color(0, 255, 0));
        updateRecords_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateRecords_btnMouseClicked(evt);
            }
        });
        jPanel1.add(updateRecords_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, -1, -1));

        jPanel2.setBackground(new java.awt.Color(127, 57, 251));

        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-minimize-20.png"))); // NOI18N
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_minimizeMousePressed(evt);
            }
        });

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-multiply-20.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_closeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_minimize)
                .addGap(27, 27, 27)
                .addComponent(btn_close)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_close)
                    .addComponent(btn_minimize))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_courseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_courseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_courseNameActionPerformed

    private void text_referenceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_referenceKeyReleased

    }//GEN-LAST:event_text_referenceKeyReleased

    private void btn_minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMousePressed
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMousePressed

    private void btn_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_closeMousePressed

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void certificateStatus_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certificateStatus_listMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_certificateStatus_listMouseClicked

    private void CourseStatus_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseStatus_listMouseClicked

    }//GEN-LAST:event_CourseStatus_listMouseClicked

    private void certificateStatus_listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_certificateStatus_listKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_certificateStatus_listKeyPressed

    private void certificateStatus_listMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certificateStatus_listMousePressed

    }//GEN-LAST:event_certificateStatus_listMousePressed

    private void certificateStatus_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateStatus_listActionPerformed
        // TODO add your handling code here:
        String selectStatus = certificateStatus_list.getSelectedItem().toString();
        System.out.println(selectStatus);
        if (certificateStatus_list.getSelectedIndex() == 1) {
            jDateChooser_certificate.setEnabled(true);
        } else {
            jDateChooser_certificate.setEnabled(false);
        }
    }//GEN-LAST:event_certificateStatus_listActionPerformed

    private void CourseStatus_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseStatus_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseStatus_listActionPerformed

    private void updateRecords_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateRecords_btnMouseClicked
        studentRecord();
    }//GEN-LAST:event_updateRecords_btnMouseClicked

    public void setReference(String reference) {
        this.reference = reference;

    }

    public void studentRecord() {
        String courseStatus = CourseStatus_list.getSelectedItem().toString();
        String certificateStatus = certificateStatus_list.getSelectedItem().toString();
        Date getDob = jDateChooser_certificate.getDate();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String certificateDate = df.format(getDob);
        String updateQuery = "update student_details set courseStatus =?,certificateStatus=?,certificateDate=? where reference='" + reference + "'";
        try {
            conn = new SQLiteDBConnection().connect();
            pst = conn.prepareStatement(updateQuery);
            pst.setString(1, courseStatus);
            pst.setString(2, certificateStatus);
            pst.setString(3, certificateDate);
            pst.execute();
            pst.close();
            conn.close();
            ImageIcon iconic = new ImageIcon(Home.class.getResource("/images/icons8-user.png"));
            JOptionPane.showMessageDialog(null, "Data Updated Successfully", "Lets Go", JOptionPane.INFORMATION_MESSAGE, iconic);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_row_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_row_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_row_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_row_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudent_row_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CourseStatus_list;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_minimize;
    public javax.swing.JComboBox<String> certificateStatus_list;
    private javax.swing.JLabel course_label1;
    private javax.swing.JLabel course_label2;
    private javax.swing.JLabel dob_label;
    private javax.swing.JLabel dob_label1;
    private javax.swing.JLabel fathersname_label2;
    private javax.swing.JLabel firstname_label;
    public com.toedter.calendar.JDateChooser jDateChooser_certificate;
    public com.toedter.calendar.JDateChooser jDateChooser_dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel mobile_label;
    private javax.swing.JLabel reference_label;
    private javax.swing.JLabel staffname_label;
    public javax.swing.JTextField text_courseName;
    public javax.swing.JTextField text_duration;
    public javax.swing.JTextField text_fatherName;
    public javax.swing.JTextField text_firstName;
    public javax.swing.JTextField text_mobileNo;
    public javax.swing.JTextField text_reference;
    public javax.swing.JTextField text_staffname;
    public javax.swing.JTextField text_timing;
    private keeptoo.KButton updateRecords_btn;
    // End of variables declaration//GEN-END:variables

}
